# Generated by Django 4.1.7 on 2023-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(upload_to='./static/uploads'),
        ),
    ]
